#!/bin/bash

# SCRIPT:
# -----------------------------
# This script creates and sends data about the host node to the Percona Telemetry service.

set -o pipefail
#set -o xtrace

# Exit script if telemetry is not be collected (only if PERCONA_TELEMETRY_DISABLE=1)
if [[ "$PERCONA_TELEMETRY_DISABLE" -ne "0" ]];
then
    exit 0;
fi

# Script variables
# Can be passed to the script via env variable or via named parameter
PERCONA_INSTANCE_ID_FILE_PATH="${PERCONA_TELEMETRY_URL:-"/tmp/telemetry_uuid"}"
PERCONA_SEND_TIMEOUT=${PERCONA_SEND_TIMEOUT:-10}
PERCONA_TELEMETRY_URL="${PERCONA_TELEMETRY_URL:-"https://127.0.0.1.nip.io/v1/telemetry/GenericReport"}"
PERCONA_PRODUCT_FAMILY=${PERCONA_PRODUCT_FAMILY}
PERCONA_PRODUCT_VERSION=${PERCONA_PRODUCT_VERSION}
PERCONA_OPERATING_SYSTEM=${PERCONA_OPERATING_SYSTEM}
PERCONA_DEPLOYMENT_METHOD=${PERCONA_DEPLOYMENT_METHOD}
PERCONA_INSTANCE_ID=${PERCONA_INSTANCE_ID}

json_message=""
declare -A json_message_map
declare -A metrics_map

## USAGE
usage()
{
    errorCode=${1:-0}

    cat << EOF

usage: $0 OPTIONS

Collects telemetry information and sends it to a Percona server. The data collection
may be disabled via setting an environment variable [PERCONA_TELEMETRY_DISABLE].

The script validates only if mandatory parameters are provided.
It does not validate the validity and itegritiy of provided parameters.

The data will be sent to $PERCONA_TELEMETRY_URL in a JSON format.

OPTIONS can be:

  -h  Show this message

  -f  [PERCONA_PRODUCT_FAMILY]          Product family identifier.                                  [REQUIRED]
  -v  [PERCONA_PRODUCT_VERSION]         Product version.                                            [REQUIRED]
  -s  [PERCONA_OPERATING_SYSTEM]        Operating system identifier.                                [REQUIRED]
  -d  [PERCONA_DEPLOYMENT_METHOD]       Deployment method.                                          [REQUIRED]
  -i  [PERCONA_INSTANCE_ID]             Instance id                                                 [Default: autogenerated]
  -j  [PERCONA_INSTANCE_ID_FILE_PATH]   Path of the file where to store the unique ID of this node. [Default: $PERCONA_INSTANCE_ID_FILE_PATH]
  -u  [PERCONA_TELEMETRY_URL]           Percona Telemetry Service endpoint                          [Default: $PERCONA_TELEMETRY_URL]
  -t  [PERCONA_SEND_TIMEOUT]            Default timeout for the curl command.                       [Default: $PERCONA_SEND_TIMEOUT]

For example,
on a CentOS7, you may run the script as:

./$0 -f "PRODUCT_FAMILY_MYSQL" -v "8.0.33" -s "\$(cat /etc/redhat-release)" -i "13f5fc62-35b4-4716-b3e6-96c761fc204d" -j /tmp/percona.telemetry -u "https://TO/DO/PROVIDE/ENDPOINT -t 1

on Ubuntu, you may run the script as:
./$0 -f "PRODUCT_FAMILY_MYSQL" -v "8.0.33" -s "\$(cat /etc/issue)" -i "13f5fc62-35b4-4716-b3e6-96c761fc204d" -j /tmp/percona.telemetry -u "https://TO/DO/PROVIDE/ENDPOINT -t 1

EOF

    if [[ $errorCode -ne 0 ]];
    then
        exit_script $errorCode
    fi
}

# Perform any required cleanup and exit with the given error/success code
exit_script()
{
    # Exit with a given return code or 0 if none are provided.
    exit ${1:-0}
}

# Vaildate arguments to ensure that mandatory ones have been provided
validate_args()
{
    local USAGE_TEXT="See usage for details."

    if [[ -z "$PERCONA_PRODUCT_FAMILY" ]];
    then
        printf "PERCONA_PRODUCT_FAMILY not provided. %s\n" "$USAGE_TEXT" >&2
        usage 1
    fi

    if [[ -z "$PERCONA_PRODUCT_VERSION" ]];
    then
        printf "PERCONA_PRODUCT_VERSION not provided. %s\n" "$USAGE_TEXT" >&2
        usage 1
    fi

    if [[ -z "$PERCONA_OPERATING_SYSTEM" ]];
    then
        printf "PERCONA_OPERATING_SYSTEM not provided. %s\n" "$USAGE_TEXT" >&2
        usage 1
    fi

    if [[ -z "$PERCONA_DEPLOYMENT_METHOD" ]];
    then
        printf "PERCONA_DEPLOYMENT_METHOD not provided. %s\n" "$USAGE_TEXT" >&2
        usage 1
    fi

    if [[ -z "$PERCONA_INSTANCE_ID" ]];
    then
        printf "PERCONA_INSTANCE_ID not provided. %s\n" "$USAGE_TEXT" >&2
        usage 1
    fi
}

# Creates the instance id file if one doesn't exist
# If instance id file exists, we already reported this instance and there is no more work to do
check_or_create_percona_instance_id_file()
{
    if [[ -f "$PERCONA_INSTANCE_ID_FILE_PATH" ]];
    then
        exit_script
    fi
    
    # If instance ID is not provided externally, generate it
    if [[ -z "$PERCONA_INSTANCE_ID" ]];
    then
        PERCONA_INSTANCE_ID=$(cat /proc/sys/kernel/random/uuid)
    fi

    echo $PERCONA_INSTANCE_ID > $PERCONA_INSTANCE_ID_FILE_PATH
}

collect_data_for_report()
{
    json_message_map["id"]=$(cat /proc/sys/kernel/random/uuid)
    json_message_map["createTime"]="$(date +"%Y-%m-%dT%H:%M:%S%:z")"
    json_message_map["instanceId"]=$PERCONA_INSTANCE_ID
    json_message_map["product_family"]=$PERCONA_PRODUCT_FAMILY

    metrics_map["pillar_version"]=$PERCONA_PRODUCT_VERSION
    # TODO:
    # On my Ubuntu, the value of /etc/issue is "Ubuntu 22.04.3 LTS \n \l"
    # Escape characters cause problems in Json, so remove them.
    # But maybe the better idea is to use values as provided and then
    # sanitize the whole json_message string after create_json_message()
    # by escaping all escape characters?
    # (see the comment at the end of collect_data_for_report())
    metrics_map["OS"]=${PERCONA_OPERATING_SYSTEM//\\/}
    metrics_map["deployment"]=$PERCONA_DEPLOYMENT_METHOD
}


# {
#    "reports":[
#       {
#          "id":"13f5fc62-35b4-4716-b3e6-96c761fc204d",
#          "createTime":"2023-09-15T13:36:53+03:00",
#          "instanceId":"6e5ff5d4-5617-11ee-8c99-0242ac120002",
#          "product_family":"PERCONA_PRODUCT_FAMILY_MYSQL",
#          "metrics":[
#             {
#                "key":"pillar_version",
#                "value":"8.0.30"
#             },
#             {
#                "key":"OS",
#                "value":"Ubuntu 22.04"
#             },
#             {
#                "key":"deployment",
#                "value":"PACKAGE"
#             }
#          ]
#       }
#    ]
# }

# Let's create a single JSON message here.
create_json_message()
{  
    json_message="{"
      json_message+="\"reports\":["
        json_message+="{"
    
          # report header
          for key in "${!json_message_map[@]}"
          do
              m="$(printf "\"%s\" : \"%s\"" "$key" "${json_message_map[$key]}")"
              json_message+="${m},"
          done
      
          # metrics
          local first_metric=1
          json_message+="\"metrics\":["
      
            for key in "${!metrics_map[@]}"
            do
                if [[ $first_metric -ne 1 ]];
                then
                  json_message+=","
                fi

                json_message+="{"
                m1="$(printf "\"key\" : \"%s\"" "$key")"
                m2="$(printf "\"value\" : \"%s\"" "${metrics_map[$key]}")"
                json_message+="${m1},"
                json_message+="${m2}"
                json_message+="}"
                first_metric=0
            done
      
          json_message+="]"   # metrics
        json_message+="}"   # reports
      json_message+="]"   # reports

    json_message+="}"

    # TODO:
    # sanitize the message (in case of any escape characters, escape them)
    # json_message=${json_message//\\/\\\\}
}

send_json_message()
{
    (curl -X POST --connect-timeout $PERCONA_SEND_TIMEOUT --header 'Content-Type: application/json' --location $PERCONA_TELEMETRY_URL --data "$json_message") &>/dev/null
}

# Check options passed in.
while getopts "h f:v:s:d:i:j:u:t:" OPTION
do
    case $OPTION in
        h)
            usage
            exit_script 1
            ;;
        f)
            PERCONA_PRODUCT_FAMILY=$OPTARG
            ;;
        v)
            PERCONA_PRODUCT_VERSION=$OPTARG
            ;;
        s)
            PERCONA_OPERATING_SYSTEM=$OPTARG
            ;;
        d)
            PERCONA_DEPLOYMENT_METHOD=$OPTARG
            ;;
        i)
            PERCONA_INSTANCE_ID=$OPTARG
            ;;
        j)
            PERCONA_INSTANCE_ID_FILE_PATH=$OPTARG
            ;;
        u)
            PERCONA_TELEMETRY_URL=$OPTARG
            ;;
        t)
            PERCONA_SEND_TIMEOUT=$OPTARG
            ;;
        ?)
            exit 0
            ;;
    esac
done

check_or_create_percona_instance_id_file

# Validate and update setup
validate_args

collect_data_for_report

# Construct the full message
create_json_message
echo $json_message

# Send the json message
send_json_message

# Perform clean up and exit.
exit_script 0
